name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches:
      - prod

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  deploy-prod:
    environment:
      name: github-pages-prod
      url: ${{ steps.build.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages (Prod)
        uses: actions/deploy-pages@v2
        with:
          branch: prod

  deploy-gh-pages:
    environment:
      name: github-pages-gh
      url: ${{ steps.build.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages (gh-pages)
        uses: actions/deploy-pages@v2
        with:
          branch: gh-pages
